"""產生 thesis refresh 實驗 config。

What:
  從 EXP-245 final protocol 派生 appendix/diagnostic 需要重跑的實驗矩陣。

Why:
  舊章節中的 noise、AL、forcing、filtering/smoothing 數據多為 10k 或 single-seed。
  這裡只改動待測因子，其他訓練 protocol 固定為 EXP-245:
  LES_T50 sensors, K=100, 1024 collocation, 20k iterations。
"""
from __future__ import annotations

import re
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
BASE_CONFIG = REPO_ROOT / "configs/stable/exp_245.toml"
OUT_DIR = REPO_ROOT / "configs/stable"

SEEDS = {
    "a": 42,
    "b": 1,
    "c": 2,
    "d": 3,
    "e": 4,
}


def _body() -> str:
    text = BASE_CONFIG.read_text(encoding="utf-8")
    marker = "[train]\n"
    if marker not in text:
        raise ValueError(f"{BASE_CONFIG} 缺少 [train] 區塊")
    return marker + text.split(marker, 1)[1]


def _set_key(text: str, key: str, value: str) -> str:
    pattern = rf"^{re.escape(key)}\s*=.*$"
    replacement = f"{key} = {value}"
    if re.search(pattern, text, flags=re.MULTILINE):
        return re.sub(pattern, replacement, text, flags=re.MULTILINE)
    anchor = "artifacts_dir = "
    idx = text.find(anchor)
    if idx == -1:
        raise ValueError(f"找不到 artifacts_dir anchor，無法插入 {key}")
    return text[:idx] + replacement + "\n" + text[idx:]


def _write(path: Path, title: str, changes: dict[str, str]) -> None:
    text = _body()
    for key, value in changes.items():
        text = _set_key(text, key, value)
    header = (
        f"# {path.name}\n"
        f"# What: {title}\n"
        "# Why: thesis refresh rerun under EXP-245 final protocol "
        "(LES_T50, 1024 collocation, 20k iterations).\n"
        "# Generated by scripts/generate_thesis_refresh_configs.py.\n\n"
    )
    path.write_text(header + text, encoding="utf-8")


def _common(exp: str, seed_tag: str, desc: str, seed: int) -> dict[str, str]:
    return {
        "seed": str(seed),
        "device": '"cuda"',
        "artifacts_dir": f'"artifacts/kolmogorov/stable/{exp}_{seed_tag}_{desc}"',
    }


def main() -> None:
    if not BASE_CONFIG.exists():
        raise FileNotFoundError(BASE_CONFIG)

    written: list[Path] = []

    # EXP-290: paper-grade sensor-noise robustness, n=5.
    noise_levels = {
        "noise01": 0.01,
        "noise03": 0.03,
        "noise05": 0.05,
        "noise10": 0.10,
    }
    for noise_tag, noise_std in noise_levels.items():
        for seed_tag, seed in SEEDS.items():
            path = OUT_DIR / f"exp_290_{noise_tag}_{seed_tag}.toml"
            changes = _common("exp_290", seed_tag, noise_tag, seed)
            changes["sensor_noise_std"] = f"{noise_std:.2f}"
            _write(
                path,
                f"EXP-290 {noise_tag} sensor-noise robustness, seed {seed}",
                changes,
            )
            written.append(path)

    # EXP-291: continuity-AL rho sweep; rho=0.1 is EXP-245 reference.
    for tag, rho in {"rho003": 0.03, "rho03": 0.3, "rho1": 1.0}.items():
        path = OUT_DIR / f"exp_291_{tag}.toml"
        changes = _common("exp_291", "a", tag, 42)
        changes["al_rho"] = f"{rho:.2f}" if rho < 1 else "1.0"
        _write(path, f"EXP-291 AL rho sweep {tag}, seed 42", changes)
        written.append(path)

    # EXP-292: multi-constraint AL under final protocol.
    multi_al = {
        "cont_pure_al": {
            "use_gradnorm": "true",
            "gradnorm_tasks": '["data", "ns_u", "ns_v"]',
            "gradnorm_init_weights": "[1.0, 0.057, 0.057]",
            "al_constraints": '["cont"]',
            "al_allow_cont_in_gradnorm": "false",
            "al_allow_ns_in_gradnorm": "false",
        },
        "full_physics_pure_al": {
            "use_gradnorm": "false",
            "gradnorm_tasks": "[]",
            "gradnorm_init_weights": "[1.0, 0.057, 0.057, 0.01]",
            "al_constraints": '["ns_u", "ns_v", "cont"]',
            "al_allow_cont_in_gradnorm": "false",
            "al_allow_ns_in_gradnorm": "false",
        },
        "ns_pure_al_cont_double": {
            "use_gradnorm": "true",
            "gradnorm_tasks": '["data", "cont"]',
            "gradnorm_init_weights": "[1.0, 0.01]",
            "al_constraints": '["ns_u", "ns_v", "cont"]',
            "al_allow_cont_in_gradnorm": "true",
            "al_allow_ns_in_gradnorm": "false",
        },
        "full_double": {
            "use_gradnorm": "true",
            "gradnorm_tasks": '["data", "ns_u", "ns_v", "cont"]',
            "gradnorm_init_weights": "[1.0, 0.057, 0.057, 0.01]",
            "al_constraints": '["ns_u", "ns_v", "cont"]',
            "al_allow_cont_in_gradnorm": "true",
            "al_allow_ns_in_gradnorm": "true",
        },
    }
    for tag, overrides in multi_al.items():
        path = OUT_DIR / f"exp_292_{tag}.toml"
        changes = _common("exp_292", "a", tag, 42)
        changes.update(overrides)
        _write(path, f"EXP-292 multi-constraint AL {tag}, seed 42", changes)
        written.append(path)

    # EXP-293: forcing identifiability under final protocol.
    forcing = {
        "learn_kf": {
            "learn_forcing_A": "false",
            "learn_forcing_k_f": "true",
            "forcing_A_init": "0.1",
            "forcing_k_f_init": "0.01",
            "forcing_k_f_min": "0.001",
            "forcing_k_f_max": "8.0",
        },
        "learn_A": {
            "learn_forcing_A": "true",
            "learn_forcing_k_f": "false",
            "forcing_A_init": "0.001",
            "forcing_k_f_init": "2.0",
        },
        "learn_both": {
            "learn_forcing_A": "true",
            "learn_forcing_k_f": "true",
            "forcing_A_init": "0.001",
            "forcing_k_f_init": "0.01",
            "forcing_k_f_min": "0.001",
            "forcing_k_f_max": "8.0",
        },
    }
    for tag, overrides in forcing.items():
        path = OUT_DIR / f"exp_293_{tag}.toml"
        changes = _common("exp_293", "a", tag, 42)
        changes.update(overrides)
        _write(path, f"EXP-293 forcing identifiability {tag}, seed 42", changes)
        written.append(path)

    # EXP-294: smoothing / bidirectional CfC vs filtering reference EXP-245.
    path = OUT_DIR / "exp_294_smoothing_bidir.toml"
    changes = _common("exp_294", "a", "smoothing_bidir", 42)
    changes["use_bidirectional_cfc"] = "true"
    _write(path, "EXP-294 smoothing bidirectional-CfC mode, seed 42", changes)
    written.append(path)

    for path in written:
        print(path.relative_to(REPO_ROOT))
    print(f"generated={len(written)}")


if __name__ == "__main__":
    main()
