"""scripts/sweep_capacity.py

CfC-DeepONet 容量診斷 sweep：固定 K=100 / DNS / seed，掃描三條容量旋鈕，
判斷「架構容量是否已飽和（plateau）vs 仍可榨取」。

設計依據（deep-research 2026-06-01，docs/research/cfc_capacity_study.md §5）：
  固定資料與感測器數，掃 width / operator-rank / liquid-τ，看 sensor MSE 與
  DNS benchmark (KE rel-err, E(k)) 是否 plateau。plateau 但離 K=100 Nyquist
  ceiling 仍有距離 → 架構/訓練瓶頸；plateau 且貼近 ceiling → 資訊論硬上限。

Sweep 矩陣（base = EXP-094 B3 dns-pivot seed=2, KE 9.4% baseline）：
  - exp_260_cap_baseline   : 對照錨點（無 override）
  - exp_261_cap_width128   : d_model 256→128（width 下界）
  - exp_262_cap_width512   : d_model 256→512（width 上界）
  - exp_263_cap_rank128    : operator_rank 256→128（rank 下界）
  - exp_264_cap_rank512    : operator_rank 256→512（rank 上界；注意 separable DeepONet
                             「大 p + 大 r 塌成 trivial solution」退化風險）
  - exp_265_cap_liquid_tau : cfc_input_dependent_tau=true（恢復 input-dependent 液態 τ）

What: 讀 base TOML → 套 override → 生成隔離 artifacts 的 config（含 provenance header）。
Why: 6 份近乎相同的手寫 TOML 違反 DRY；generator 讓 sweep 可重跑、override 一目了然。

預設 dry-run：只生成 config + 印執行計畫（不燒計算）。
  uv run python scripts/sweep_capacity.py                 # 生成 config + 印計畫
  uv run python scripts/sweep_capacity.py --run           # 依序 train+eval 全部變體
  uv run python scripts/sweep_capacity.py --run --only exp_265_cap_liquid_tau

注意（KNOWN_PITFALLS）：
  - resume 系統禁用 → 每個變體必須 1-shot 從 scratch 跑完，勿中斷。
  - 改 d_model 屬架構變更 → 冷啟動（本來就是新 artifacts，無 resume 風險）。
  - 訓練前須 export PYTORCH_ENABLE_MPS_FALLBACK=1（SOAP eigh 需 CPU fallback）。
"""
from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BASE_CONFIG = ROOT / "configs" / "exp_094_b3_seed2.toml"
GEN_DIR = ROOT / "configs" / "generated"
ARTIFACT_ROOT = "artifacts/kolmogorov/cap_sweep"

# 每個變體：相對 base 的 override（其餘繼承 EXP-094 baseline）。
SWEEP: list[dict] = [
    {"id": "exp_260_cap_baseline",   "axis": "baseline",  "desc": "對照錨點（= EXP-094 B3, static τ, d_model=256, rank=256）", "overrides": {}},
    {"id": "exp_261_cap_width128",   "axis": "width",     "desc": "width↓: d_model 256→128", "overrides": {"d_model": 128}},
    {"id": "exp_262_cap_width512",   "axis": "width",     "desc": "width↑: d_model 256→512", "overrides": {"d_model": 512}},
    {"id": "exp_263_cap_rank128",    "axis": "rank",      "desc": "rank↓: operator_rank 256→128", "overrides": {"operator_rank": 128}},
    {"id": "exp_264_cap_rank512",    "axis": "rank",      "desc": "rank↑: operator_rank 256→512（separable DeepONet 大p+大r 退化風險）", "overrides": {"operator_rank": 512}},
    {"id": "exp_265_cap_liquid_tau", "axis": "liquid-τ",  "desc": "cfc_input_dependent_tau=true（恢復 input-dependent 液態時間常數）", "overrides": {"cfc_input_dependent_tau": True}},
]


def toml_value(v: object) -> str:
    """最小 TOML scalar 序列化（涵蓋 sweep override 用到的型別）。"""
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(v)
    if isinstance(v, str):
        return f'"{v}"'
    raise TypeError(f"sweep override 不支援的型別: {type(v)} ({v!r})")


def _line_key(line: str) -> str | None:
    """從 `key = value` 行抽 key（忽略註解 / section / 空行）。"""
    s = line.strip()
    if not s or s.startswith("#") or s.startswith("["):
        return None
    if "=" not in s:
        return None
    return s.split("=", 1)[0].strip()


def generate_config(variant: dict) -> Path:
    """讀 base raw text → 行替換 override / artifacts_dir → 加 provenance header → 寫出。"""
    base_text = BASE_CONFIG.read_text()
    overrides: dict = dict(variant["overrides"])
    artifacts_dir = f"{ARTIFACT_ROOT}/{variant['id']}"

    out_lines: list[str] = []
    seen: set[str] = set()
    for line in base_text.splitlines():
        key = _line_key(line)
        if key == "artifacts_dir":
            out_lines.append(f'artifacts_dir = "{artifacts_dir}"')
            continue
        if key in overrides:
            out_lines.append(f"{key} = {toml_value(overrides[key])}")
            seen.add(key)
            continue
        out_lines.append(line)

    # base 未含的 override key（如 cfc_input_dependent_tau）append 到檔尾（仍屬 [train]）。
    missing = [k for k in overrides if k not in seen]
    if missing:
        out_lines.append("")
        out_lines.append("# --- capacity sweep override（base 未含的欄位）---")
        for k in missing:
            out_lines.append(f"{k} = {toml_value(overrides[k])}")

    ov_str = ", ".join(f"{k}={v}" for k, v in overrides.items()) or "（無，對照錨點）"
    header = [
        f"# {variant['id']} — capacity sweep [{variant['axis']}]",
        f"# What: {variant['desc']}",
        f"# Provenance: generated by scripts/sweep_capacity.py from {BASE_CONFIG.name}",
        f"# Override vs base: {ov_str}",
        "# 判讀見 docs/research/cfc_capacity_study.md §5（plateau vs Nyquist ceiling）。",
        "",
    ]
    GEN_DIR.mkdir(parents=True, exist_ok=True)
    out_path = GEN_DIR / f"{variant['id']}.toml"
    out_path.write_text("\n".join(header + out_lines) + "\n")
    return out_path


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--run", action="store_true", help="實際執行 train+eval（預設僅生成 config + 印計畫）。")
    p.add_argument("--only", type=str, default=None, help="只處理指定 variant id（如 exp_265_cap_liquid_tau）。")
    p.add_argument("--device", choices=["auto", "cpu", "mps", "cuda"], default=None, help="覆蓋 config device。")
    return p.parse_args()


def main() -> None:
    args = parse_args()
    if not BASE_CONFIG.exists():
        print(f"[ERROR] base config 不存在: {BASE_CONFIG}", file=sys.stderr)
        sys.exit(1)

    variants = [v for v in SWEEP if args.only is None or v["id"] == args.only]
    if not variants:
        print(f"[ERROR] --only '{args.only}' 不在 sweep 矩陣；可選: {[v['id'] for v in SWEEP]}", file=sys.stderr)
        sys.exit(1)

    print("=== capacity sweep ===")
    print(f"base:      {BASE_CONFIG}")
    print(f"mode:      {'RUN (train+eval)' if args.run else 'DRY-RUN (generate config only)'}")
    print(f"variants:  {len(variants)}\n")

    generated: list[tuple[dict, Path]] = []
    for v in variants:
        cfg_path = generate_config(v)
        generated.append((v, cfg_path))
        print(f"  [{v['axis']:>8}] {v['id']:<24} → {cfg_path.relative_to(ROOT)}")
        print(f"             {v['desc']}")

    if not args.run:
        print("\n[dry-run] config 已生成。檢視後加 --run 執行；或單跑：")
        print("  uv run python scripts/sweep_capacity.py --run --only <id>")
        print("\n提醒: export PYTORCH_ENABLE_MPS_FALLBACK=1；每個變體 1-shot 跑完勿中斷（resume 禁用）。")
        return

    for v, cfg_path in generated:
        print(f"\n>>> [{v['id']}] train+eval")
        cmd = ["uv", "run", "python", "scripts/run_experiment.py", "--config", str(cfg_path)]
        if args.device:
            cmd += ["--device", args.device]
        result = subprocess.run(cmd)
        if result.returncode != 0:
            print(f"[ERROR] variant {v['id']} 失敗 (rc={result.returncode})；中止 sweep。", file=sys.stderr)
            sys.exit(result.returncode)

    print("\n=== sweep done ===")
    print("提取各變體 KE rel-err / E(k) slope → 填 docs/research/cfc_capacity_study.md §5 判讀表。")


if __name__ == "__main__":
    main()
